### ISSUE TITLE
Failing to start `TzUpdatePeriodically`

### ISSUE THREAD

**Issue by sodapopcan** [mathieuprog/tz#29]
Hi there!

Today I randomly started getting an error without any code changes:

```
** (Mix) Could not start application my_app: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: Tz.UpdatePeriodically
    ** (EXIT) an exception was raised:
        ** (ArithmeticError) bad argument in arithmetic expression
            :erlang.+(nil, 1)
            (tz 0.26.5) lib/tz/iana_file_parser.ex:338: Tz.IanaFileParser.month_string_to_integer/1
            (tz 0.26.5) lib/tz/iana_file_parser.ex:144: Tz.IanaFileParser.transform_rule/1
            (tz 0.26.5) lib/tz/iana_file_parser.ex:53: Tz.IanaFileParser.parse_strings_into_maps/2
            (tz 0.26.5) lib/tz/iana_file_parser.ex:67: Tz.IanaFileParser.parse_strings_into_maps/2
            (tz 0.26.5) lib/tz/iana_file_parser.ex:14: Tz.IanaFileParser.parse/1
            (tz 0.26.5) lib/tz/compiler.ex:20: anonymous fn/2 in Tz.Compiler.compile/0
            (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
            (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
            (tz 0.26.5) lib/tz/compiler.ex:18: Tz.Compiler.compile/0
            (tz 0.26.5) lib/tz/updater.ex:23: Tz.Updater.maybe_recompile/0
            (tz 0.26.5) lib/tz/update_periodically.ex:31: Tz.UpdatePeriodically.init/1
            (stdlib 5.2) gen_server.erl:980: :gen_server.init_it/2
            (stdlib 5.2) gen_server.erl:935: :gen_server.init_it/6
            (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
I've been actively working on this application the past couple of weeks without running into this (I've never run into it!) and just started happening today.
```

I have tried `rm -rf _build deps ~/.hex` to no avail.

I'm a bit out of date on my stack:

Erlang 26.2
Elixir 1.16.2

I'll perhaps try upgrading but wanted to report regardless. Let me know if there is any other information I can provide.

Thank you!

**Comment by mathieuprog** [comment]
Update to 0.27.2

**Comment by sodapopcan** [comment]
Ah, my bad.  I had also tried this but wasn't paying attention and didn't realize I had to manually bump the version.

Thank you so much and sorry for the bother!

**Comment by jstlroot** [comment]
Hey @mathieuprog! Thank you for the great lib and the quick fix. ❤️

This problem took down my app in production, and I was wondering what your thoughts would be on these 2 points:

1. Should I refrain from using this lib in production since it's not yet stable? I know and understand that there is no guarantee of any sort and I'm not asking for anything like that. I'm just wondering if this kind of problem is likely to happen in the future.
2. If it's not a bad idea to keep using it, is there a better way of configuring it so that it doesn't crash the app but still apply updates periodically?

Thank you!

**Comment by mathieuprog** [comment]
It's actually stable and intend to release a 1.0 version soon enough 

Could you explain how it took your app down in production?

The Updater should be running in a process, do you know why your whole app crashed and how we can avoid this?

**Comment by mathieuprog** [comment]
@jstlroot I had another look at it and the updater shouldn't make your app crash (can we see the stack trace?).

Instead, I think that you or your deployment process tried to start the application and `tz` was blocking you because it couldn't compile the 2024b IANA files. It should not crash an already running app in prod. However, it might have prevented a deployment.

Could you please confirm?

Note that all the time zone libraries suffer from 2024b including time zone databases in other programming languages:
https://lists.iana.org/hyperkitty/list/tz@iana.org/thread/Y5KABB56LLOPHQJL4MFHWHSLR7KJ2XSP/
https://lists.iana.org/hyperkitty/list/tz@iana.org/thread/LBVCBNK5NPWBNQ5UDUY3YEZPWA2QV262/
https://lists.iana.org/hyperkitty/list/tz@iana.org/thread/6PF5BB7342JR6PALTMQFEGU2FZ5ADW36/
etc.

**Comment by jstlroot** [comment]
@mathieuprog Thank you for your prompt answers. I'm happy to know the lib is stable. Let's hope IANA files won't keep changing format without notice.

My app is young and the logs are not yet persisted between deployments, it's something I'm planning to configure in the coming days. So I'm sorry I won't be able to provide the exact context (stack trace) for the crash.

Reading your last message, I thought it might have been DigitalOcean's App Platform applying an automated update and restarting my app that caused the issue. However, when I tried rollbacking the TZ update and deploying it on my staging environment this morning, when it failed, App Platform gracefully rollbacked to the working version as expected, avoiding any downtime:

![image](https://github.com/user-attachments/assets/926009de-e945-498c-803a-41067420a56c)

So I'm not 100% sure what happened. I should have copied the stack trace yesterday but was in a rush, I'm sorry about that. I remember seeing `bad argument in arithmetic expression` and it being a problem with `month_string_to_integer/1`.

Please don't hesitate to ask if you have any other questions.

**Comment by whmountains** [comment]
This also took down several of my apps in production.  @mathieuprog, as you guessed, in at least one case I was able to confirm that the app was restarted due to an unrelated deploy or config change and it failed to start thereafter.

EDIT: for others reading this thread I see that 0.28 was released recently with a change to prevent errors from blocking startup.  Thanks!

**Comment by mathieuprog** [comment]
@whmountains this was fixed in 0.28.x

**Comment by mathieuprog** [comment]
1. it was a mistake to start the Updater's work on `init`, as the updater code has side effects such as http calls and parsing external iana files. So I start the work in `handle_continue` instead of `init` to avoid crashing the app on start.

2. i added a try/rescue to avoid flooding the server with error logs in case of error (because the supervisor would indefinitely try to restart the genserver, which would keep failing because of the iana files).

**Comment by spacebat** [comment]
I had a late night debugging this in production - kubernetes + elixir app startup crashes are quite the combo. Luckily its a background service I'm working on that produces output daily so no customers would notice. Sounds like ~ 0.28 is the go, thanks @mathieuprog!
